INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('1', '1', 'Codes Table Reference Title', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('1', '2', 'Medical History Questions', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('1', '3', 'Physical Ailments', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '1', 'Are you presently under medical treatment?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '2', 'Has a physician informed you that you have:', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '3', 'Have you had any major operation?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '4', 'Are you allergic to any food or medicine?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '5', 'Do you experience shortness of breath when climbing upstairs?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '6', 'Have you experienced any complications with healing?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '7', 'Are you in good general health all this time?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('2', '8', 'Are you pregnant?', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '1', 'Heart Ailment', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '2', 'High Blood Pressure', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '3', 'Diabetes', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '4', 'Rheumatic Heart Fever', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '5', 'Lung Disease', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '6', 'Tumors or growth', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '7', 'Any liver disease', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '8', 'Any kidney disease', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '9', 'Any blood disease', '1');
INSERT INTO `jawsmith_program`.`table_maintenance` (`REF_ID`, `CODE_TBL_VALUE`, `DESCRIPTION`, `STATUS`) VALUES ('3', '10', 'Stomach or intestinal problem', '1');
